### ISSUE TITLE
No context menu for macOS

### ISSUE THREAD

**Issue by YuraPostevka** [terror2012/electronApp#10]
![2020-12-15_11-24-47](https://user-images.githubusercontent.com/22457568/102197436-d3eff880-3ec9-11eb-9cc7-9e6eaabef0a6.png)

for windows when we run the app, it adds app in app toolbar and also adding this to tray
for mac if I use "yarn start" script it shows the app in tray, if I install the app from .dmg file it runs the app as regular macOS app (and there is no way to open context menu)

**Comment by YuraPostevka** [comment]
macOS. because of missing context menu Im not able to change api key

**Comment by terror2012** [comment]
Added a fix where I used a nativeImage instead of a icon path, which should solve the missing tray
