### ISSUE TITLE
link installer EULA to web page

### ISSUE THREAD

**Issue by mulyoved** [terror2012/electronApp#13]
link installer EULA to web page

https://testrtc.com/terms/

Ask the user to accept, simmilar to the attached image 

![image](https://user-images.githubusercontent.com/2309907/102376233-16016300-3fcc-11eb-95a6-062c1c2b5b02.png)

**Comment by terror2012** [comment]
Will solve it in the next commit and close this issue.

**Comment by terror2012** [comment]
Fixed in the latest commit
