### ISSUE TITLE
api key is not stored permanently

### ISSUE THREAD

**Issue by YuraPostevka** [terror2012/electronApp#14]
- user open installed app
- "change api key" modal pops up
- user enter api key
- app started working
all is good

then
- user quit the app at all (tray-context menu-stop)
- user open app again
-  "change api key" modal pops up
this is bug because app should use previously stored api key (btw it works fine if I use "yarn start" script (locally)) :((

I saw in the code next line

fs.writeFileSync(path.join(__dirname, "resources", "config.json"), JSON.stringify(configJSON));

looks this line is not working with installed app.

any thoughts on this or how can it be fixed?

**Comment by terror2012** [comment]
There's a problem with file-based storage, I'll look into it and solve it in the next commit. Apparently it won't create the resources file, and persist the API key on app exit

**Comment by terror2012** [comment]
Fixed in the commit
