### ISSUE TITLE
installer name case should be probeRTC

### ISSUE THREAD

**Issue by mulyoved** [terror2012/electronApp#15]
![image](https://user-images.githubusercontent.com/2309907/102803820-87bd2080-43c1-11eb-847c-524c52515852.png)

**Comment by terror2012** [comment]
Solved in the next commit, also changed the readme, since the building command is not electron-builder build, it's just electron-builder and the flags (--win ... )

**Comment by mulyoved** [comment]
![image](https://user-images.githubusercontent.com/2309907/102910197-d7175580-4482-11eb-8b2f-5c73052918dc.png)
