### ISSUE TITLE
installer name still not correct

### ISSUE THREAD

**Issue by mulyoved** [terror2012/electronApp#18]
![image](https://user-images.githubusercontent.com/2309907/102910252-f0200680-4482-11eb-87b9-063d0f7d31a9.png)

**Comment by mulyoved** [comment]
![image](https://user-images.githubusercontent.com/2309907/102910281-f9a96e80-4482-11eb-9e7e-c71c7ee5f4a9.png)

**Comment by mulyoved** [comment]
![image](https://user-images.githubusercontent.com/2309907/102910360-1ba2f100-4483-11eb-8489-083de5423b02.png)

**Comment by mulyoved** [comment]
![image](https://user-images.githubusercontent.com/2309907/102910412-31181b00-4483-11eb-8302-81e57cf17167.png)

**Comment by terror2012** [comment]
![image](https://user-images.githubusercontent.com/9155285/102915449-87d52300-448a-11eb-9092-d2c2681b8cb1.png)

Got the above image running electron-builder --win on the latest commit resulted in this launcher.
The latest commit is set to version 1.0.0.
The builder uses productName from the build part of package.json for the name. Make sure it's set to probeRTC.
Please leave a comment if it's not fixed. If the productName is not probeRTC, change it to probeRTC. Thanks
