### ISSUE TITLE
use bitbucket

### ISSUE THREAD

**Issue by YuraPostevka** [terror2012/electronApp#2]
1. can we use bitbucket?
2. if so, can you point us to how we can configure it. Im trying to use it with bitbucket repo.

**Comment by terror2012** [comment]
Unfortunately, electron-builder auto-update doesn't support bitbucket.
As stated in this issue: https://github.com/megahertz/electron-simple-updater/issues/41 , you'd need to create a custom provider. 
Electron-builder, out of the box, supports the following providers: GitHub Releases, Amazon S3, DigitalOcean Spaces, Bintray and generic HTTP(s) server.

**Comment by mulyoved** [comment]
Will use S3

**Comment by mulyoved** [comment]
Can close this one
