### ISSUE TITLE
Uninstall fail on windows

### ISSUE THREAD

**Issue by mulyoved** [terror2012/electronApp#8]
![image](https://user-images.githubusercontent.com/2309907/102195945-e9fcb980-3ec7-11eb-97a1-4790a97d3fed.png)

**Comment by terror2012** [comment]
https://github.com/electron-userland/electron-builder/issues/4875
Apparently there's a confirmed bug when it comes to building for windows on macOS.
I used a fix from that issue (by creating a custom nsh script), that will be on the next commit.
Please let me know if it works properly
